version: "3.7"
services:
  minecraft:
    image: itzg/minecraft-server:java17
    container_name: minecraft
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      EULA: "TRUE"
      VERSION: 1.18
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/better-minecraft.zip
      SERVER_NAME: "Better Minecraft [FORGE]"
      USE_MODPACK_START_SCRIPT: true
      OPS: makreeltje_
    stdin_open: true
    volumes:
      - ${CONF_DIR}/minecraft/data:/data
      - ${CONF_DIR}/minecraft/modpacks:/modpacks
    ports:
      - 25565:25565
    tty: true