version: "3.7"
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack-new/download/3555525/file
    stdin_open: true
    volumes:
      - ${CONF_DIR}/minecraft/data:/data
    ports:
      - 25565:25565
    tty: true