version: "3.7"
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: better-minecraft.zip
    stdin_open: true
    volumes:
      - ${CONF_DIR}/minecraft/data:/data
    ports:
      - 25565:25565
    tty: true